name: assistrend  # Your project name (lowercase_with_underscores)
description: A Flutter application for ASSISTREND
version: 1.0.0+1  # Version number (adjust as needed)

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.22.0'  # Add Flutter constraint if needed

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.0.15 
  google_sign_in: ^6.1.0
  google_sign_in_web: ^0.12.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


dependency_overrides:
  async: ^2.13.0
  fake_async: ^1.3.3
  material_color_utilities: ^0.12.0
  # Add other packages as needed

# flutter:
#   assets:
#     - assets/fonts/NotoSans-Regular.ttf
#   fonts:
#     - family: NotoSans
#       fonts:
#         - asset: assets/fonts/NotoSans-Regular.ttf
